#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'


require 'strscan'

module SimpleDB

class Parser < Racc::Parser

module_eval(<<'...end sdb-parser.y/module_eval...', 'sdb-parser.y', 156)

KEYWORDS = %w(
  AND
  ASC
  BETWEEN
  BY
  CREATE
  DELETE
  DESCRIBE
  DESC
  DOMAINS
  DOMAIN
  DROP
  EVERY
  FROM
  GET
  INSERT
  INTERSECTION
  INTO
  IN
  IS
  ITEMNAME
  LIKE
  LIMIT
  NOT
  ORDER
  OR
  REGIONS
  SET
  SHOW
  UPDATE
  USE
  VALUES
  WHERE
)

KEYWORD_REGEXP = Regexp.compile("#{KEYWORDS.join '|'}\\b", Regexp::IGNORECASE)

def initialize(obj)
  src = obj.is_a?(IO) ? obj.read : obj.to_s
  @ss = StringScanner.new(src)
end

@@structs = {}

def struct(name, attrs = {})
  unless (clazz = @@structs[name])
    clazz = attrs.empty? ? Struct.new(name.to_s) : Struct.new(name.to_s, *attrs.keys)
    @@structs[name] = clazz
  end

  obj = clazz.new

  attrs.each do |key, val|
    obj.send("#{key}=", val)
  end

  return obj
end
private :struct

def scan
  tok = nil

  until @ss.eos?
    if (tok = @ss.scan /\s+/)
      # nothing to do
    elsif (tok = @ss.scan /(?:!=|>=|<=|>|<|=)/)
      yield [tok, tok]
    elsif (tok = @ss.scan KEYWORD_REGEXP)
      yield [tok.upcase.to_sym, tok]
    elsif (tok = @ss.scan /SELECT\b/i)
      yield [:SELECT, tok + @ss.scan(/.*/)]
    elsif (tok = @ss.scan /NULL\b/i)
      yield [:NULL, nil]
    elsif (tok = @ss.scan /`([^`]|``)*`/)
      yield [:IDENTIFIER, tok.slice(1...-1).gsub(/``/, '`')]
    elsif (tok = @ss.scan /'([^']|'')*'/) #'
      yield [:VALUE, tok.slice(1...-1).gsub(/''/, "'")]
    elsif (tok = @ss.scan /"([^"]|"")*"/) #"
      yield [:VALUE, tok.slice(1...-1).gsub(/""/, '"')]
    elsif (tok = @ss.scan /(0|[1-9]\d*)/)
      yield [:NATURAL_NUMBER, tok.to_i]
    elsif (tok = @ss.scan /[,\(\)\*]/)
      yield [tok, tok]
    elsif (tok = @ss.scan /[a-z_$][-0-9a-z_$.]*\b/i)
      yield [:IDENTIFIER, tok]
    else
      raise Racc::ParseError, ('parse error on value "%s"' % @ss.rest.inspect)
    end
  end

  yield [false, '$']
end
private :scan

def parse
  yyparse self, :scan
end

def self.parse(obj)
  self.new(obj).parse
end

...end sdb-parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    12,    59,    27,    58,    81,    57,    82,    25,    13,    52,
    58,    60,    57,    64,    14,    65,    15,    16,    17,    36,
    18,    19,    34,    35,    20,    21,    22,    37,    38,    39,
    40,    41,    42,    43,    44,    41,    45,    46,    47,    48,
    49,    33,    53,    54,    32,    27,    61,    62,    63,    29,
    66,    52,    68,    69,    70,    71,    28,    73,    74,    75,
    76,    77,    78,    80,    23,    83 ]

racc_action_check = [
     0,    50,    12,    49,    79,    49,    79,    12,     0,    43,
    65,    50,    65,    55,     0,    55,     0,     0,     0,    20,
     0,     0,    19,    19,     0,     0,     0,    21,    22,    23,
    24,    26,    28,    29,    30,    31,    32,    33,    40,    41,
    42,    18,    44,    47,    17,    15,    52,    53,    54,    14,
    59,    60,    61,    62,    63,    64,    13,    66,    69,    70,
    71,    73,    74,    76,     1,    82 ]

racc_action_pointer = [
    -2,    64,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    -2,    45,    45,    41,   nil,    23,    20,    -2,
    15,    23,    24,    29,    27,   nil,    16,   nil,    28,    16,
    31,    20,    32,    33,   nil,   nil,   nil,   nil,   nil,   nil,
    34,    35,    28,     5,    38,   nil,   nil,    38,   nil,    -1,
    -4,   nil,    39,    42,    42,     0,   nil,   nil,   nil,    44,
    47,    44,    47,    47,    41,     6,    50,   nil,   nil,    51,
    51,    48,   nil,    53,    54,   nil,    55,   nil,   nil,    -9,
   nil,   nil,    57,   nil ]

racc_action_default = [
   -39,   -39,    -1,    -2,    -3,    -4,    -5,    -6,    -7,    -8,
    -9,   -10,   -12,   -39,   -39,   -25,   -27,   -39,   -39,   -39,
   -39,   -39,   -39,   -39,   -39,   -13,   -14,   -35,   -39,   -39,
   -39,   -26,   -39,   -39,   -30,   -31,   -32,   -33,   -34,    84,
   -39,   -39,   -39,   -39,   -39,   -28,   -29,   -39,   -36,   -39,
   -39,   -21,   -39,   -39,   -39,   -39,   -16,   -18,   -19,   -39,
   -39,   -39,   -39,   -39,   -39,   -39,   -39,   -22,   -23,   -39,
   -39,   -39,   -17,   -39,   -39,   -11,   -39,   -20,   -24,   -39,
   -37,   -15,   -39,   -38 ]

racc_goto_table = [
    51,    26,    56,    10,    31,     5,     6,     7,     8,     9,
     4,    11,    24,     1,    55,    79,     3,    67,    72,    50,
     2,    30 ]

racc_goto_check = [
    18,    13,    16,    10,    13,     5,     6,     7,     8,     9,
     4,    11,    12,     1,    14,    15,     3,    18,    16,    17,
     2,    19 ]

racc_goto_pointer = [
   nil,    13,    20,    16,    10,     5,     6,     7,     8,     9,
     3,    11,     0,   -11,   -35,   -61,   -47,   -24,   -43,     6 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  8, 31, :_reduce_11,
  0, 41, :_reduce_12,
  1, 41, :_reduce_13,
  1, 41, :_reduce_none,
  10, 32, :_reduce_15,
  1, 43, :_reduce_16,
  3, 43, :_reduce_17,
  1, 45, :_reduce_none,
  1, 45, :_reduce_none,
  8, 33, :_reduce_20,
  1, 46, :_reduce_21,
  3, 46, :_reduce_22,
  3, 47, :_reduce_23,
  8, 34, :_reduce_24,
  0, 48, :_reduce_25,
  1, 48, :_reduce_none,
  1, 35, :_reduce_27,
  3, 36, :_reduce_28,
  3, 37, :_reduce_29,
  2, 38, :_reduce_30,
  2, 38, :_reduce_31,
  2, 39, :_reduce_32,
  2, 40, :_reduce_33,
  2, 40, :_reduce_34,
  1, 42, :_reduce_35,
  3, 42, :_reduce_36,
  1, 44, :_reduce_37,
  3, 44, :_reduce_38 ]

racc_reduce_n = 39

racc_shift_n = 84

racc_token_table = {
  false => 0,
  :error => 1,
  :GET => 2,
  :FROM => 3,
  :IDENTIFIER => 4,
  :WHERE => 5,
  :ITEMNAME => 6,
  "=" => 7,
  :VALUE => 8,
  "*" => 9,
  :INSERT => 10,
  :INTO => 11,
  "(" => 12,
  ")" => 13,
  :VALUES => 14,
  "," => 15,
  :UPDATE => 16,
  :SET => 17,
  :DELETE => 18,
  :SELECT => 19,
  :CREATE => 20,
  :DOMAIN => 21,
  :DROP => 22,
  :SHOW => 23,
  :DOMAINS => 24,
  :REGIONS => 25,
  :USE => 26,
  :DESC => 27,
  :DESCRIBE => 28 }

racc_nt_base = 29

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "GET",
  "FROM",
  "IDENTIFIER",
  "WHERE",
  "ITEMNAME",
  "\"=\"",
  "VALUE",
  "\"*\"",
  "INSERT",
  "INTO",
  "\"(\"",
  "\")\"",
  "VALUES",
  "\",\"",
  "UPDATE",
  "SET",
  "DELETE",
  "SELECT",
  "CREATE",
  "DOMAIN",
  "DROP",
  "SHOW",
  "DOMAINS",
  "REGIONS",
  "USE",
  "DESC",
  "DESCRIBE",
  "$start",
  "stmt",
  "get_stmt",
  "insert_stmt",
  "update_stmt",
  "delete_stmt",
  "select_stmt",
  "create_stmt",
  "drop_stmt",
  "show_stmt",
  "use_stmt",
  "desc_stmt",
  "get_output_list",
  "identifier_list",
  "insert_identifier_list",
  "value_list",
  "itemname_identifier",
  "set_clause_list",
  "set_clause",
  "delete_attr_list" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

module_eval(<<'.,.,', 'sdb-parser.y', 16)
  def _reduce_11(val, _values)
                    struct(:GET, :domain => val[3], :item_name => val[7], :attr_names => val[1])
             
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 21)
  def _reduce_12(val, _values)
                          []
                    
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 25)
  def _reduce_13(val, _values)
                          []
                    
  end
.,.,

# reduce 14 omitted

module_eval(<<'.,.,', 'sdb-parser.y', 31)
  def _reduce_15(val, _values)
                    unless val[4].length == val[8].length
                  raise Racc::ParseError, 'The number of an attribute and values differs'
                end

                attrs = {}
                val[4].zip(val[8]).each {|k, v| attrs[k] = v }
                item_name = attrs.find {|k, v| k =~ /\AitemName\Z/i }

                unless item_name
                  raise Racc::ParseError,'itemName is not contained in the INSERT statement'
                end

                attrs.delete(item_name[0])
                item_name = item_name[1]

                struct(:INSERT, :domain => val[2], :item_name => item_name, :attrs => attrs)
              
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 52)
  def _reduce_16(val, _values)
                                 [val[0]]
                           
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 56)
  def _reduce_17(val, _values)
                                 val[0] + [val[2]]
                           
  end
.,.,

# reduce 18 omitted

# reduce 19 omitted

module_eval(<<'.,.,', 'sdb-parser.y', 64)
  def _reduce_20(val, _values)
                    attrs = {}
                val[3].each {|k, v| attrs[k] = v }
                struct(:UPDATE, :domain => val[1], :items => [[val[7], attrs]])
              
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 71)
  def _reduce_21(val, _values)
                          [val[0]]
                    
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 75)
  def _reduce_22(val, _values)
                          val[0] + [val[2]]
                    
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 80)
  def _reduce_23(val, _values)
                     [val[0], val[2]]
               
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 85)
  def _reduce_24(val, _values)
                      struct(:DELETE, :domain => val[3], :items => [[val[7], val[1]]])
                
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 90)
  def _reduce_25(val, _values)
                           []
                     
  end
.,.,

# reduce 26 omitted

module_eval(<<'.,.,', 'sdb-parser.y', 96)
  def _reduce_27(val, _values)
                      struct(:SELECT, :query => val[0])
                
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 101)
  def _reduce_28(val, _values)
                      struct(:CREATE, :domain => val[2])
                
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 106)
  def _reduce_29(val, _values)
                    struct(:DROP, :domain => val[2])
              
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 111)
  def _reduce_30(val, _values)
                    struct(:SHOW, :operand => :domains)
              
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 115)
  def _reduce_31(val, _values)
                    struct(:SHOW, :operand => :regions)
              
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 119)
  def _reduce_32(val, _values)
                   struct(:USE, :endpoint => val[1])
             
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 123)
  def _reduce_33(val, _values)
                    struct(:DESCRIBE, :domain => val[1])
              
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 127)
  def _reduce_34(val, _values)
                    struct(:DESCRIBE, :domain => val[1])
              
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 132)
  def _reduce_35(val, _values)
                                   [val[0]]
                             
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 136)
  def _reduce_36(val, _values)
                                   val[0] + [val[2]]
                             
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 141)
  def _reduce_37(val, _values)
                               [val[0]]
                         
  end
.,.,

module_eval(<<'.,.,', 'sdb-parser.y', 145)
  def _reduce_38(val, _values)
                              [val[0], val[2]].flatten
                         
  end
.,.,

def _reduce_none(val, _values)
  val[0]
end

end   # class Parser


end # module SimpleDB
